// frontend/src/pages/DocumentList.tsx
import { useEffect } from 'react'
import { Table, Button, Tag, Space, Typography, message, Popconfirm, Card, Statistic } from 'antd'
import { DeleteOutlined, ReloadOutlined, SettingOutlined, FileOutlined } from '@ant-design/icons'
import { useDocumentStore } from '@/stores/documentStore'
import { formatFileSize, formatTime, getStatusColor, getStatusText } from '@/utils/format'

const { Title, Text } = Typography

export default function DocumentList() {
  const { documents, stats, loading, total, fetchDocuments, refreshAll, deleteDocument, initKB } =
    useDocumentStore()

  useEffect(() => {
    refreshAll()
  }, [])

  const handleDelete = async (docId: string, fileName: string) => {
    try {
      await deleteDocument(docId)
      message.success(`已删除 ${fileName}`)
    } catch {
      message.error('删除失败')
    }
  }

  const handleInitKB = async () => {
    try {
      await initKB()
      message.success('知识库初始化成功')
    } catch {
      message.error('初始化失败')
    }
  }

  const columns = [
    {
      title: '文件名',
      dataIndex: 'file_name',
      key: 'file_name',
      render: (text: string) => (
        <Space>
          <FileOutlined />
          <Text>{text}</Text>
        </Space>
      ),
    },
    {
      title: '类型',
      dataIndex: 'file_type',
      key: 'file_type',
      width: 100,
      render: (text: string) => <Tag>{text.toUpperCase()}</Tag>,
    },
    {
      title: '大小',
      dataIndex: 'file_size',
      key: 'file_size',
      width: 100,
      render: (size: number) => formatFileSize(size),
    },
    {
      title: '分块数',
      dataIndex: 'chunk_count',
      key: 'chunk_count',
      width: 100,
      align: 'center' as const,
      render: (count: number) => <Tag>{count}</Tag>,
    },
    {
      title: '状态',
      dataIndex: 'status',
      key: 'status',
      width: 100,
      render: (status: string) => (
        <Tag color={getStatusColor(status)}>{getStatusText(status)}</Tag>
      ),
    },
    {
      title: '入库时间',
      dataIndex: 'created_at',
      key: 'created_at',
      width: 150,
      render: (time: string) => formatTime(time),
    },
    {
      title: '操作',
      key: 'action',
      width: 100,
      render: (_: any, record: any) => (
        <Popconfirm
          title="确定删除此文档？"
          description="删除后不可恢复"
          onConfirm={() => handleDelete(record.doc_id, record.file_name)}
          okText="确定"
          cancelText="取消"
        >
          <Button type="text" danger icon={<DeleteOutlined />}>
            删除
          </Button>
        </Popconfirm>
      ),
    },
  ]

  return (
    <div style={{ padding: '24px 32px' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 24 }}>
        <div>
          <Title level={2} style={{ marginBottom: 8 }}>知识库文档</Title>
          <Text type="secondary">
            共 {stats?.total_documents || 0} 个文档，{stats?.collection?.points_count || 0} 个向量分块
          </Text>
        </div>
        <Space>
          <Button icon={<ReloadOutlined />} onClick={() => refreshAll()} loading={loading}>
            刷新
          </Button>
          <Button type="primary" icon={<SettingOutlined />} onClick={handleInitKB}>
            初始化知识库
          </Button>
        </Space>
      </div>

      <Table
        columns={columns}
        dataSource={documents}
        rowKey="doc_id"
        loading={loading}
        pagination={{ pageSize: 20 }}
        locale={{ emptyText: '暂无文档，请先上传文档到知识库' }}
      />
    </div>
  )
}

// frontend/src/views/knowledge/DocumentList.vue
<script setup lang="ts">
import { onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useDocumentStore } from '@/stores/document'
import { deleteDocument } from '@/api/document'
import { initKnowledgeBase } from '@/api/knowledgeBase'
import { formatFileSize, formatTime, getStatusType } from '@/utils/format'

const documentStore = useDocumentStore()

onMounted(() => {
  documentStore.refreshAll()
})

async function handleDelete(docId: string, fileName: string) {
  try {
    await ElMessageBox.confirm(
      `确定要删除文档 "${fileName}" 吗？删除后不可恢复。`,
      '确认删除',
      { type: 'warning' },
    )
    await deleteDocument(docId)
    ElMessage.success('删除成功')
    documentStore.refreshAll()
  } catch {
    // cancelled or error
  }
}

async function handleInitKB() {
  try {
    await ElMessageBox.confirm(
      '初始化知识库将创建 Qdrant 向量集合。已有集合不受影响。是否继续？',
      '初始化知识库',
      { type: 'info' },
    )
    await initKnowledgeBase()
    ElMessage.success('知识库初始化成功')
    documentStore.refreshAll()
  } catch {
    // cancelled or error
  }
}

function handleRefresh() {
  documentStore.refreshAll()
  ElMessage.success('已刷新')
}
</script>

<template>
  <div class="document-list">
    <div class="page-header">
      <div class="header-left">
        <h2>知识库文档</h2>
        <p class="subtitle" v-if="documentStore.stats">
          共 {{ documentStore.stats.total_documents }} 个文档，
          {{ documentStore.stats.collection.points_count ?? 0 }} 个向量分块
        </p>
      </div>
      <div class="header-actions">
        <el-button @click="handleRefresh" :loading="documentStore.loading">
          <el-icon><Refresh /></el-icon>
          刷新
        </el-button>
        <el-button type="primary" @click="handleInitKB">
          <el-icon><Setting /></el-icon>
          初始化知识库
        </el-button>
      </div>
    </div>

    <div class="table-container">
      <el-table
        :data="documentStore.documents"
        v-loading="documentStore.loading"
        stripe
        style="width: 100%"
        empty-text="暂无文档，请先上传文档到知识库"
      >
        <el-table-column prop="file_name" label="文件名" min-width="200">
          <template #default="{ row }">
            <div class="file-name-cell">
              <el-icon :size="16"><Document /></el-icon>
              <span>{{ row.file_name }}</span>
            </div>
          </template>
        </el-table-column>

        <el-table-column prop="file_type" label="类型" width="100">
          <template #default="{ row }">
            <el-tag size="small" type="info">{{ row.file_type.toUpperCase() }}</el-tag>
          </template>
        </el-table-column>

        <el-table-column prop="file_size" label="大小" width="100">
          <template #default="{ row }">
            {{ formatFileSize(row.file_size) }}
          </template>
        </el-table-column>

        <el-table-column prop="chunk_count" label="分块数" width="100" align="center">
          <template #default="{ row }">
            <el-tag size="small">{{ row.chunk_count }}</el-tag>
          </template>
        </el-table-column>

        <el-table-column prop="status" label="状态" width="100">
          <template #default="{ row }">
            <el-tag :type="getStatusType(row.status)" size="small">
              {{ row.status === 'completed' ? '完成' : row.status }}
            </el-tag>
          </template>
        </el-table-column>

        <el-table-column prop="created_at" label="入库时间" width="140">
          <template #default="{ row }">
            {{ formatTime(row.created_at) }}
          </template>
        </el-table-column>

        <el-table-column label="操作" width="100" fixed="right">
          <template #default="{ row }">
            <el-button
              type="danger"
              text
              size="small"
              @click="handleDelete(row.doc_id, row.file_name)"
            >
              <el-icon><Delete /></el-icon>
              删除
            </el-button>
          </template>
        </el-table-column>
      </el-table>
    </div>
  </div>
</template>

<style scoped lang="scss">
.document-list {
  padding: 24px 32px;
  height: 100%;
  overflow-y: auto;
}

.page-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-bottom: 24px;

  .header-left {
    h2 {
      font-size: 22px;
      font-weight: 600;
      color: #303133;
      margin-bottom: 8px;
    }

    .subtitle {
      color: #909399;
      font-size: 14px;
    }
  }

  .header-actions {
    display: flex;
    gap: 12px;
  }
}

.table-container {
  background: #fff;
  border-radius: 12px;
  padding: 16px;
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.04);
}

.file-name-cell {
  display: flex;
  align-items: center;
  gap: 8px;
  color: #303133;

  .el-icon {
    color: #909399;
    flex-shrink: 0;
  }

  span {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
}
</style>
